### ISSUE TITLE
Typing search text block browser UI

### ISSUE THREAD

**Issue by tillda** [domkm/omelette#2]
Because of the novelty of this (great) project I don't know why is this happening: when I'm typing the search term the browser sometimes does not respond. 

It does not happen always, but usually when I delete the term and start typing another one.

**Comment by domkm** [comment]
Thanks for your feedback.

I think you can temporarily fix this by reducing the maximum number of results [here](https://github.com/DomKM/omelette/blob/9beceed80734a44425906deb1f8c33e6802a1407/src/omelette/data.clj#L31). I changed it to `50` and didn't notice any freezing.

This project is unconcerned with performance issues that are not related to isomorphic architecture. The [word matching algorithm](https://github.com/DomKM/omelette/blob/9beceed80734a44425906deb1f8c33e6802a1407/src/omelette/data.clj#L5-31) is terribly inefficient. Rendering results is even worse since they are displayed twice and don't make use of React's `key` property.

I'll probably reduce the maximum number of results since freezing could detract from the purpose of the project.
